### ISSUE TITLE
Flächennutzung Landkreis oder Belzig

### ISSUE THREAD

**Issue by juliahebestreit** [Klima-Dashboard/data-tools#14]
- Anteile der Flächennutzung
- Jahreswert
- Aktualisierung: jährlich, manuell
- Quellen: [Statistische Ämter des Bundes und der Länder](https://github.com/Klima-Dashboard/data-tools/wiki/Datenquellen#statistische-ämter-des-bundes-und-der-länder)

Aufteilung in Unter-Items:

[Flächennutzung: Anteil versiegelt (Siedlung/Verkehr) vs. nicht versiegelt (Landwirtschaft, Wald)#38](https://github.com/Klima-Dashboard/data-tools/issues/38)

**Comment by juliahebestreit** [comment]
https://regionalatlas.statistikportal.de
Welche Anteile der Flächennutzung sind relevant? Siehe Auswahl in Screenshots

![Image](https://user-images.githubusercontent.com/117658146/203809184-16ecb16e-e66d-453d-9eec-c03a14265baf.png)
![Image](https://user-images.githubusercontent.com/117658146/203809185-73dbe348-f311-4233-bfa3-5ce113f90505.png)

**Comment by pwilimzig** [comment]
Nach Auswahl der gewünschten Daten sind diese über die "Open Data" Funktion herunterladbar: 

![Image](https://user-images.githubusercontent.com/664428/204524009-446ed609-e921-4f9d-b6ac-66f73728bf2a.png)

**Comment by EricMuelling** [comment]
Anteil der Fläche für Wald und Landwirtschaft (evtl. auch Verkehrsfläche) wären von Bedeutung.

**Comment by EricMuelling** [comment]
Gibt es die Daten für den Landkreis oder auch für nur für Bad Belzig?
