### ISSUE TITLE
E-Mobilität, Ladestationen im Fläming

### ISSUE THREAD

**Issue by juliahebestreit** [Klima-Dashboard/data-tools#53]
- Karte mit Standorten
- Einzelinformationen
- Aktualisierung: jährlich, manuell
- Kategorie: Mobilität
- Quellen:  [Marktstammdatenregister](https://github.com/Klima-Dashboard/data-tools/wiki/Datenquellen#marktstammdatenregister)

Gleiches Thema taucht mit anderer Quelle hier auf: https://github.com/Klima-Dashboard/data-tools/issues/11

**Comment by pwilimzig** [comment]
Doublette
